behaviors:
  HallwayAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1000
      learning_rate: 3.0e-4
    network_settings:
      num_layers: 2
      hidden_units: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000
    time_horizon: 64
    summary_freq: 1000